module.exports = {
  prefix: '',
  important: false,
  separator: ':',
  theme: {
    screens: {},
    colors: {},
    spacing: {},
    backgroundColor: {},
    backgroundPosition: {},
    backgroundSize: {},
    borderColor: {},
    borderRadius: {},
    borderWidth: {},
    boxShadow: {},
    container: {},
    cursor: {},
    fill: {},
    flex: {},
    flexGrow: {},
    flexShrink: {},
    fontFamily: {},
    fontSize: {},
    fontWeight: {},
    height: {},
    inset: {},
    letterSpacing: {},
    lineHeight: {},
    listStyleType: {},
    margin: {},
    maxHeight: {},
    maxWidth: {},
    minHeight: {},
    minWidth: {},
    objectPosition: {},
    opacity: {},
    order: {},
    padding: {},
    stroke: {},
    textColor: {},
    width: {},
    zIndex: {},
  },
  variants: {
  },
  corePlugins: {},
  plugins: [],
}
